import { createFileRoute } from '@tanstack/react-router'
import { ogImageMeta } from "@/lib/seo/meta";
import { DocLayout } from '@/components/site/DocLayout'
import { SITE_URL } from '@/lib/site'

const URL = `${SITE_URL}/disclaimer`
const TITLE = 'Medical / Legal Disclaimer — Shutap'
const DESCRIPTION =
  'Shutap writes jokes, not prescriptions. It does not provide medical, mental-health, crisis, or legal services or advice.'

export const Route = createFileRoute('/disclaimer')({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: 'description', content: DESCRIPTION },
      { property: 'og:title', content: TITLE },
      { property: 'og:description', content: DESCRIPTION },
      { property: 'og:type', content: 'website' },
      { property: 'og:url', content: URL },
      ...ogImageMeta(),
      { name: 'twitter:title', content: TITLE },
      { name: 'twitter:description', content: DESCRIPTION },
    ],
    links: [{ rel: 'canonical', href: URL }],
  }),
  component: DisclaimerPage,
})

function DisclaimerPage() {
  return (
    <DocLayout
      active="/disclaimer"
      title="Medical / Legal Disclaimer"
      subline="formal + in-voice"
    >
      <h3>Formal</h3>
      <p>
        Shutap is a pseudonymous entertainment service that generates AI-written humorous content
        (&ldquo;joke cards&rdquo;) from user-submitted situations. It does not provide medical,
        psychological, mental-health, crisis, or legal services or advice, and no professional
        relationship is created by using it. In an emergency, contact 988 or 911 (US) or
        findahelpline.com. 18+.
      </p>
      <p>
        Cards are generated by AI and may be inaccurate, unfunny, or inappropriate. The
        &ldquo;Mirror&rdquo; describes patterns across the cards you chose to keep; it is an
        observation, not an assessment, diagnosis, or recommendation. A paid membership buys cards
        without the shutap mark and the Mirror&rsquo;s patterns, never advice, treatment, or relief.
        Daily allowances (five situations a day, at every tier) are cost controls and may change.
      </p>

      <h3>In-voice</h3>
      <div
        style={{
          background: '#fff',
          border: '.5px solid rgba(11,8,15,.08)',
          borderRadius: 14,
          padding: '16px 18px',
          fontFamily: 'Newsreader,serif',
          fontStyle: 'italic',
          fontSize: 15.5,
          color: '#3a2630',
          lineHeight: 1.55,
        }}
      >
        shutap writes jokes, not prescriptions. not therapy, not advice, not a diagnosis. paying
        gets you more cards and cleaner ones — never a cure. if it&apos;s heavy, here&apos;s real help \u2192
      </div>
    </DocLayout>
  )
}
